run:
  timeout: 10m
  build-tags:
    - integration
    - linux

issues:
  exclude-dirs:
    - artifacts
    - build-targets
    - design
    - docker-images
    - docs
    - etc
    - experiments
    - infrastructure
    - legal
    - libpf-rs
    - mocks
    - pf-code-indexing-service/cibackend/gomock_*
    - pf-debug-metadata-service/dmsbackend/gomock_*
    - pf-host-agent/support/ci-kernels
    - pf-storage-backend/storagebackend/gomock_*
    - scratch
    - systemtests/benchmarks/_outdata
    - target
    - virt-tests
    - vm-images

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Don't complain about integer overflows
    - text: "G115:"
      linters:
        - gosec

linters:
  enable-all: true
  disable:
    # Disabled because of
    #   - too many non-sensical warnings
    #   - not relevant for us
    #   - false positives
    #
    # "might be worth fixing" means we should investigate/fix in the mid term
    - containedctx # might be worth fixing
    - contextcheck # might be worth fixing
    - cyclop
    - depguard
    - dupword
    - durationcheck # might be worth fixing
    - err113
    - errorlint # might be worth fixing
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert # might be worth fixing
    - funlen
    - gci # might be worth fixing
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox # complains about TODO etc
    - gofumpt
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - nestif
    - nilerr # might be worth fixing
    - nilnil
    - nlreturn
    - noctx # might be worth fixing
    - nonamedreturns
    - paralleltest
    - protogetter
    - sqlclosecheck # might be worth fixing
    - tagalign
    - tagliatelle
    - testableexamples # might be worth fixing
    - testpackage
    - tparallel # might be worth fixing
    - thelper
    - varnamelen
    - wastedassign
    - wsl
    - wrapcheck
    # the following linters are deprecated
    - exportloopref
    # we don't want to change code to Go 1.22+ yet
    - intrange
    - copyloopvar

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - whyNoLint
      - sloppyReassign
      - uncheckedInlineErr # Experimental rule with high false positive rate.
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - debug,debugf,debugln
          - error,errorf,errorln
          - fatal,fatalf,fataln
          - info,infof,infoln
          - log,logf,logln
          - warn,warnf,warnln
          - print,printf,println,sprint,sprintf,sprintln,fprint,fprintf,fprintln
  lll:
    line-length: 100
    tab-width: 4
  misspell:
    locale: US
    ignore-words:
      - rela
