// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_def.go

package usdt

type ArgType = uint32

const (
	ArgConst    = 0x0
	ArgReg      = 0x1
	ArgRegDeref = 0x2
)

type Register = uint8

const (
	RegNone = 0x0

	RegRax = 0x1
	RegRbx = 0x2
	RegRcx = 0x3
	RegRdx = 0x4
	RegRsi = 0x5
	RegRdi = 0x6
	RegRbp = 0x7
	RegRsp = 0x8
	RegR8  = 0x9
	RegR9  = 0xa
	RegR10 = 0xb
	RegR11 = 0xc
	RegR12 = 0xd
	RegR13 = 0xe
	RegR14 = 0xf
	RegR15 = 0x10
	RegRip = 0x11

	RegX0  = 0x20
	RegX1  = 0x21
	RegX2  = 0x22
	RegX3  = 0x23
	RegX4  = 0x24
	RegX5  = 0x25
	RegX6  = 0x26
	RegX7  = 0x27
	RegX8  = 0x28
	RegX9  = 0x29
	RegX10 = 0x2a
	RegX11 = 0x2b
	RegX12 = 0x2c
	RegX13 = 0x2d
	RegX14 = 0x2e
	RegX15 = 0x2f
	RegX16 = 0x30
	RegX17 = 0x31
	RegX18 = 0x32
	RegX19 = 0x33
	RegX20 = 0x34
	RegX21 = 0x35
	RegX22 = 0x36
	RegX23 = 0x37
	RegX24 = 0x38
	RegX25 = 0x39
	RegX26 = 0x3a
	RegX27 = 0x3b
	RegX28 = 0x3c
	RegX29 = 0x3d
	RegX30 = 0x3e
	RegSP  = 0x3f
	RegPC  = 0x40
)

type ArgSpec struct {
	Val_off      uint64
	Arg_type     uint32
	Reg_id       uint8
	Arg_signed   bool
	Arg_bitshift int8
	Arg_is_float bool
	X_pad        [1]uint8
	Pad_cgo_0    [7]byte
}

type Spec struct {
	Args        [12]ArgSpec
	Usdt_cookie uint64
	Arg_cnt     int16
	X_pad       [6]uint8
}
