// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/profiling component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("profiling")
	ScopeName = "go.opentelemetry.io/ebpf-profiler/collector"
)

const (
	ProfilesStability = component.StabilityLevelDevelopment
)
