// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/kprobe component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("kprobe")
	ScopeName = "go.opentelemetry.io/ebpf-profiler/probes/kprobe"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
