// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/processcontext/processcontext.proto

package processcontext

import (
	v11 "go.opentelemetry.io/proto/slim/otlp/common/v1"
	v1 "go.opentelemetry.io/proto/slim/otlp/resource/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessContext contains OpenTelemetry SDK-published process-level resource
// attributes, as specified in OTEP #4719.
type ProcessContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resource contains the Resource attributes published by the SDK
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// extra_attributes contains additional key-value pairs beyond resource
	ExtraAttributes []*v11.KeyValue `protobuf:"bytes,2,rep,name=extra_attributes,json=extraAttributes,proto3" json:"extra_attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessContext) Reset() {
	*x = ProcessContext{}
	mi := &file_proto_processcontext_processcontext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContext) ProtoMessage() {}

func (x *ProcessContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processcontext_processcontext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContext.ProtoReflect.Descriptor instead.
func (*ProcessContext) Descriptor() ([]byte, []int) {
	return file_proto_processcontext_processcontext_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessContext) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ProcessContext) GetExtraAttributes() []*v11.KeyValue {
	if x != nil {
		return x.ExtraAttributes
	}
	return nil
}

var File_proto_processcontext_processcontext_proto protoreflect.FileDescriptor

const file_proto_processcontext_processcontext_proto_rawDesc = "" +
	"\n" +
	")proto/processcontext/processcontext.proto\x12\x0eprocesscontext\x1a.opentelemetry/proto/resource/v1/resource.proto\x1a*opentelemetry/proto/common/v1/common.proto\"\xab\x01\n" +
	"\x0eProcessContext\x12E\n" +
	"\bresource\x18\x01 \x01(\v2).opentelemetry.proto.resource.v1.ResourceR\bresource\x12R\n" +
	"\x10extra_attributes\x18\x02 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\x0fextraAttributesB8Z6go.opentelemetry.io/ebpf-profiler/proto/processcontextb\x06proto3"

var (
	file_proto_processcontext_processcontext_proto_rawDescOnce sync.Once
	file_proto_processcontext_processcontext_proto_rawDescData []byte
)

func file_proto_processcontext_processcontext_proto_rawDescGZIP() []byte {
	file_proto_processcontext_processcontext_proto_rawDescOnce.Do(func() {
		file_proto_processcontext_processcontext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processcontext_processcontext_proto_rawDesc), len(file_proto_processcontext_processcontext_proto_rawDesc)))
	})
	return file_proto_processcontext_processcontext_proto_rawDescData
}

var file_proto_processcontext_processcontext_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_processcontext_processcontext_proto_goTypes = []any{
	(*ProcessContext)(nil), // 0: processcontext.ProcessContext
	(*v1.Resource)(nil),    // 1: opentelemetry.proto.resource.v1.Resource
	(*v11.KeyValue)(nil),   // 2: opentelemetry.proto.common.v1.KeyValue
}
var file_proto_processcontext_processcontext_proto_depIdxs = []int32{
	1, // 0: processcontext.ProcessContext.resource:type_name -> opentelemetry.proto.resource.v1.Resource
	2, // 1: processcontext.ProcessContext.extra_attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_processcontext_processcontext_proto_init() }
func file_proto_processcontext_processcontext_proto_init() {
	if File_proto_processcontext_processcontext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processcontext_processcontext_proto_rawDesc), len(file_proto_processcontext_processcontext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_processcontext_processcontext_proto_goTypes,
		DependencyIndexes: file_proto_processcontext_processcontext_proto_depIdxs,
		MessageInfos:      file_proto_processcontext_processcontext_proto_msgTypes,
	}.Build()
	File_proto_processcontext_processcontext_proto = out.File
	file_proto_processcontext_processcontext_proto_goTypes = nil
	file_proto_processcontext_processcontext_proto_depIdxs = nil
}
