// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/heap component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("heap")
	ScopeName = "go.opentelemetry.io/ebpf-profiler/probes/heap"
)

const (
	ExtensionsStability = component.StabilityLevelDevelopment
)
