name: Collector Tests
on:
  workflow_dispatch:
  schedule:
    # Run every day at 3:15 AM.
    - cron: '15 3 * * *'
  pull_request:
    branches: ["**"]
    paths:
      - cmd/otelcol-ebpf-profiler/manifest.yaml
      - .github/workflows/collector-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up environment
        uses: ./.github/workflows/env
      - name: Set up Go Stable
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: stable
      - name: Cache coredump modules
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: tools/coredump/modulecache
          key: coredumps-collector-${{ hashFiles('tools/coredump/testdata/*/*.json') }}
          restore-keys: |
            coredumps-collector
            coredumps-
      - name: Clone Collector
        run: |
          collector_path=/tmp/opentelemetry-collector
          git clone --depth=1 https://github.com/open-telemetry/opentelemetry-collector.git $collector_path
      - name: Setup replace statement
        run: |
          COLLECTOR_PATH=/tmp/opentelemetry-collector ./support/local-collector.sh
          # Add replace directives to internal/tools for genproto and ebpf-profiler
          go mod edit -modfile=internal/tools/go.mod -replace='google.golang.org/genproto@v0.0.0-20220519153652-3a47de7e79bd=google.golang.org/genproto@v0.0.0-20260226221140-a57be14db171'
          go mod edit -modfile=internal/tools/go.mod -replace='google.golang.org/genproto/googleapis/rpc@v0.0.0-20220519153652-3a47de7e79bd=google.golang.org/genproto/googleapis/rpc@v0.0.0-20260226221140-a57be14db171'
          go mod edit -modfile=internal/tools/go.mod -replace="go.opentelemetry.io/ebpf-profiler=$(pwd)"
          go mod tidy
          go mod tidy -modfile=internal/tools/go.mod
          # Manual run of go generate and go mod tidy to have a clean start for make test-junit
          go generate ./...
          go mod tidy
          go mod tidy -modfile=internal/tools/go.mod
      - name: Tests
        run: make test-junit
      - name: Generate Issue
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install go.opentelemetry.io/build-tools/issuegenerator@v0.28.1
          issuegenerator -path /tmp/testresults

  otelcol-ebpf-profiler:
    strategy:
      matrix:
        include:
          - { runner: ubuntu-24.04, use-upstream: true }
          - { runner: ubuntu-24.04, use-upstream: false }
          - { runner: ubuntu-24.04-arm, use-upstream: true }
          - { runner: ubuntu-24.04-arm, use-upstream: false }
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Go Stable
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: stable
      - name: Clone Collector
        if: ${{ matrix.use-upstream }}
        run: |
          collector_path=/tmp/opentelemetry-collector
          git clone --depth=1 https://github.com/open-telemetry/opentelemetry-collector.git $collector_path
      - name: Setup replace statements
        if: ${{ matrix.use-upstream }}
        run: |
          COLLECTOR_PATH=/tmp/opentelemetry-collector make otel-from-tree
      - name: Build otelcol-ebpf-profiler
        run: |
          make otelcol-ebpf-profiler
      - name: Generate Issue
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install go.opentelemetry.io/build-tools/issuegenerator@v0.28.1
          issuegenerator -path /tmp/testresults
