name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "31 6 * * 4" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@9ba7b96740beb68158e4f1cdfd10a3b794364711 # v0.8.0
