name: OSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "31 6 * * 4" # once a week
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read # for actions/checkout
      id-token: write # for Scorecard to publish results
      security-events: write # for the SARIF upload to code scanning
    uses: open-telemetry/shared-workflows/.github/workflows/scorecard.yml@ee32c419ea90b05286c0cdc24538d970992cf82a # v0.11.0
